#!/usr/bin/env bash

set -euxo pipefail

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <version>"
    exit 1
fi

go build -x -ldflags="-X 'main.version=$1' -X 'main.builtAt=$(date -u -Is | sed "s/\+00:00$/Z/")'" -o energieprijzen ./cmd/bot
