#!/usr/bin/env bash

# We don't use -e because "gum confirm" exits with 1 if the user says no.
set -uo pipefail

LAST_TAG=$(git describe --tags --abbrev=0)
LAST_VERSION=$(echo "$LAST_TAG" | cut -d. -f3)
NEXT_VERSION=$((LAST_VERSION + 1))
NEXT_TAG="v1.0.$NEXT_VERSION"

if gum confirm --default=no --affirmative="Yep! 🤩" --negative="Never mind. 😬" "Would you like to release $NEXT_TAG?"; then
    git tag $NEXT_TAG
    gum spin --show-output --spinner="line" --title="Releasing $NEXT_TAG..." -- git push --atomic origin main $NEXT_TAG
    exit 0
fi

echo "No worries. Maybe next time. 😊"
